# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('start_date', models.CharField(max_length=20)),
                ('n_children', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('n_adults', models.CharField(max_length=20)),
                ('breakfast', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('spa', models.BooleanField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
